---
title: "The Daily Dose (2021)"
output:
  html_document:
    theme: default
    highlight: textmate
    css: styles.css
    toc: true
    toc_float: yes
---

## December

### 2021-12-31

- [x] EMOM x20 Minutes
  - 1x Deadlift (315 lbs)
  - 2x Back Squat (225 lbs)
  - 3x Power Clean (205 lbs)
  - 4x Power Snatch (155 lbs)

### 2021-12-30

- [x] 6x Rounds:
  - 10x Push-Ups
  - 4x Hang squat cleans
  - 16x Walking lunges (8x per leg)
  - 6x Deadlifts

### 2021-12-29

  - [x] 4x Rounds:
    - 25x DB Thrusters
    - 25x DB Ground-to-Overhead
    - 25x DB Deadlifts
    - 25x DB Push-Presses
    - 25x DB Front Squats

### 2021-12-28

- [x] 3x Rounds:
  - 8x DB Devil's Press
  - 8x DB Thrusters
  - 8x DB Power Cleans
  - 8x DB Burpees
  - 8x DB Hang Clusters

### 2021-12-27

- [x] 5x Rounds:
  - 20x DB Snatches
  - 15x DB Push Press
  - 10x DB Deadlifts

### 2021-12-26

- [x] 8x Rounds Of:
  - 5x Back Squats
  - 12x KB Swings
  - 2x Power Clean + Hang Power Clean

### 2021-12-25

*rest*

### 2021-12-24

*rest*

### 2021-12-23

- [x] 5x Rounds Of:
  - 20x Ball Slams
  - 10x Box Jumps
  - 10x Burpees

### 2021-12-22

- [x] EMOM x 20 Min:
  - 10x DB Alternating Snatch  
     (65 lbs, 75 lbs)
  - 5x Deadlifts  
     (225 lbs, 275 lbs)

### 2021-12-21

- [x] 10x Rounds Of:
  - 3x Barbell Power Cleans
    - (185 lbs)
  - 10x DB Hang Clean
    - (55 lbs)

### 2021-12-20

- [x] 8x Rounds Of:
  - 5x Back Squat  
    - 225 lbs
  - 12x KB Swings  
    - 55 lbs
  - 20x Double-Unders  

### 2021-12-19

- [x] Snatch Workout
  - Work up to heavy triple power snatch
  - Power Snatch + Overhead Squat (heavy triple weight)

### 2021-12-18

- [x] 6x Rounds Of:
  - 5x Double DB Ground-to-Overhead
  - 5x DB Burpees
  - 20x Double-Unders

### 2021-12-17

- [x] EMOM x21 Min:
  - 10x DB Snatch (50 lbs)
  - 10x DB Hang Clean + Press (50 lbs)
  - 6x BB Front Squat (95 lbs)

### 2021-12-16

- [x] Barbell Complex x 10:
  - Power Clean, Push-Press, 2x Back Squat, 2x Behind-the-neck Jerk
    - (185, 205 lbs)  
  - Then 5x5 Overhand-Grip Deadlifts:  
    - (225 lbs)  

### 2021-12-15

- [x] AMAP (in 25 min):
  - Barbell Walking Lunge (95 lbs)
  - D-Ball Toss (50 lbs)
  - Turkish Get-Up (65 lbs)

- [x] 3x Rounds Of:
  - 20x Double Unders
  - 10x DB Alternating Snatch (60 lbs)

### 2021-12-14

- [x] Barbell Workout
  - work up to heavy triple OHS  
  - (135, 155, 185, 205 lbs)
Then 4x Rounds Of:  
  - 5x Overhead Squat (70%)
  - 10x DB Clean + Press (65 lbs)

### 2021-12-13

- [x] 8x Rounds Of:
  - 5x Barbell Back-squats
    - *start at bodyweight, go up 10 lbs each set
  - 5x Barbell Thrusters
    - (115 lbs)

### 2021-12-12

- [x] EMOM x20 Minutes:
  - 2x DB Rows + 3x Devils Press + 4x Front Squat

### 2021-12-11

- [x] 5x Rounds Of:
  - 5x Barbell Front Squat (135 lbs, 155 lbs, 185 lbs)
  - 12x DB Singel Arm Thruster
  - 1x Barbell Power Clean + Jerk (185 lbs)

### 2021-12-10

- [x] EMOM x 21 Min
  - 25x Double-Unders
  - 10x DB Alternating Snatch
  - 12x DB Bench Press

### 2021-12-09

- [x] 5x Rounds:
  - 8-8-8-6-6x Barbell Lunges  
    (135/185/205 lbs)  
  - 12-12-10-10-10x KB Snatches    
    (55/70 lbs)  

### 2021-12-08

- [x] Barbell workout  
 - Work up to heavy triple FS  
   - (185 lbs, 205 lbs, 225 lbs)  
 - 5x Rounds of:  
   - 10x Deadlift (155 lbs)  
   - 12x DB Hang Snatch (50 lbs)  

### 2021-12-07

- [x] Barbell Work  
  - Back Squat 5x5 70-80%  
  - PC & J + HPC & J (3x3)  
  - PS + HPS (4x2)  
  - DB hang clean + press (3x10)  

### 2021-12-06

- [x] 10x Rounds  
  - 10x DB Single Arm Snatches (from floor)  
  - 10x DB Push-Press  
  - 6x Weighted Step-Ups  

### 2021-12-05

- [x] EMOM x 18 Min:
  - 20x KB Swings
  - 15x Push-Ups

### 2021-12-04

- [x] 3 Rounds:
  - 30x Squats
  - 20x DB Hang Power Clean + Jerk
  - 10x Single Arm Devil's Press

### 2021-12-03

- [x] 8x Rounds
(…hotel room workout…)
  - 20x Squat
  - 15x Push-Ups
  - 9x Sit Ups
  - 6x Lunges

### 2021-12-02

- [x] 4x Rounds Of:  
(…hotel room workout…)  
  - 25x Squats  
  - 25x Push-Ups  

### 2021-12-01

- [x] 15-10-5-10-15x Reps Of:  
  - DB Ground-to-Overhead  
  - DB Weighted Step-Overs  
  - Push-Ups  
  
## November

### 2021-11-31

- [x] AMRAP x20 Minutes:
  - 20x Single Arm Devil's Press
  - 20x Goblet Squats

### 2021-11-30

- [x] 5x Rounds Of:
  - 5x DB Devil’s Clean
  - 20x DB Alt. Hang Power Snatch

### 2021-11-29

- [x] EMOM x36 Minutes
  - 3x Man-Makers
  - 6x DB Thrusters
  - 9x DB Hang Clean + Press
  - 12x DB Single Arm Alternating Snatch
  - 15x DB Deadlifts

### 2021-11-28

- [x] 5x Rounds:
  - 6x DB Power Cleans
  - 8x DB Push Press
  - 10x DB Squat

### 2021-11-27

- [x] 10x Rounds
  - 5x Double DB Ground-to-Overhead
  - 5x Burpees
  - 5x D-Ball Tosses

### 2021-11-26

- [x] 30x Rounds Of:
  - 1x DB Devils Press
  - 2x DB Thrusters
  - 3x DB Deadlifts

### 2021-11-25

- [x] 10-9-8-7-6-5-4-3-3-3 Reps Of:
  - DB Curls
  - DB Bench Press
  - DB Goblet Squat

### 2021-11-24

- [x] 3x Rounds:
  - 10x DB Snatches (R)
  - 10x DB Overhead Lunges (R)
  - 10x DB Snatches (L)
  - 10x DB Overhead Lunges (L)
  - 10x DB Power Cleans (R)
  - 10x DB Front Squats (R)
  - 10x DB Power Cleans (L)
  - 10x DB Front Squats (L)

### 2021-11-23

- [x] EMOM x 21 Minutes:
  - 1x DB Deadlift
  - 2x DB Hang Power Clean
  - 3x DB Shoulder-to-Overhead

### 2021-11-22

- [x] 5x Rounds Of:
  - 15x DB Clean + Press
  - 15x DB Front Squat

### 2021-11-21

- [x] EMOM x27 Minutes:
  - 10x DB Deadlifts
  - 20x Double-Unders
  - 15x Push-Ups

### 2021-11-20

- [x] 100x Reps Of:
  - DB Clean + 2x Reverse Lunges + 1x Front Squat

### 2021-11-19

- [x] 3x Rounds Of:
  - 7-5-3x Reps of
    - DB Ground-to-Overheads
    - DB Thrusters
    - DB Step Overs

### 2021-11-18

- [x] 30 Seconds Work/Rest (4x Rounds):
  - KB Single Arm Hang Clean + Press
  - KB Goblet Squat
  - KB Single Arm Snatch + Overhead Lunge
  - KB Switch Hand Swing

### 2021-11-17

- [x] EMOM x27 Minutes
  - 10x Weighted Sit-Ups
  - 12x DB Single Arm Hang Clean + Split Jerk
  - 25x Double-Unders

### 2021-11-16

- [x] 10x Rounds Of (30 sec work/rest):
  - DB Hammer Curls
  - DB Standing Press
  - DB Front Squat
  - DB Bench Press

### 2021-11-15

- [x] EMOM x21 Minutes
  - 12x Push-Ups
  - 10x KB Deadlifts
  - 8x KB Push-Press


### 2021-11-14

- [x] 2x Rounds Of:
  - 50x reps of:
    - DB Single Arm Cleans + Press
  - Then 5x Minutes Of:
    - Max DB Single Arm Snatch
    - *only rest overhead*

### 2021-11-13

- [x] 1000x Weighted Step-Ups
  - 25 lbs Weight Vest

### 2021-11-12

- [x] 10-8-6-4-2x Reps Of:
  - Devils Press
  - 10x Lunges (*after each round)

### 2021-11-11

- [x] 1 Round Of:
  - 10-8-6-4-2 reps of:
    - DB Cleans (50 lbs, 55 lbs, 65 lbs)
  - 12-12-12-12-12 reps of:
    - Kneeling Ball Slams



### 2021-11-10

- [x] 10x Rounds Of:
  - 10x DB Alternating Snatch
  - 10x DB Goblet Squat
  - 10x DB Hang Power Clean and Press
  - 10x DB Front Squat


### 2021-11-09

- [x] EMOM x21 Minutes:
  - 10x DB Deadlift
  - 16x DB Hammer Curls
  - 14x DB Alternating Seated Press


### 2021-11-08

- [x] 3x Rounds Of:
  - 10x Bulgarian Split Squats
  - 10x Strict Overhead Presses

- [x] 4x Rounds Of:
  - 10x DB Step-Ups
  - 10x Goblet Squats
  - 10x Hammer Curls

### 2021-11-07

- [x] 3x Rounds Of:
  - 10x DB Power Cleans
  - 10x DB Front Squats
  - 15x DB Push-Press

### 2021-11-06

- [x] 10x Rounds Of:
  - 2x D-Ball to Shoulder + Squat
  - 20x Double Unders
  - 12x Ab Rotations

### 2021-11-05

- [x] 5x Rounds Of:
  - 20x Push-Ups
  - 20x Squats
  - 20x Sit-Ups

### 2021-11-04

- [x] 1 Min On/1 Min Off x 25 Min:
  - DB Hang Power Snatch
  - DB Hang Power Clean + Press
  - DB Front Squat

*start at 50 lbs, go up in weight until you can’t*

### 2021-11-03

- [x] 50x Reps Of:
  - TB Hang Clean
  - TB Rack Reverse Lunge
  - TB Push-Press



### 2021-11-02

- [x] 10x Rounds Of:
  - 10x KB/DB Snatch
  - 10x KB/DB Overhead Lunge
  - 20m Single Arm Rack Carry



### 2021-11-01

- [x] EMOM x20 Minutes:
  - 3x sets of:
    - KB Snatch
      - KB Press
        - KB Front Squat
          - KB Hang Clean + Press

(switch sides each minute)

## October

### 2021-10-31

- [x] 3x Rounds:
  - 12x DB Push-ups
  - 10x DB Deadlifts
  - 8x DB Front Rack Reverse Lunges
  - 6x DB Push-press
  - 4x DB Ground-to-Overhead
  - 2x DB Burpees



### 2021-10-30

- [x] 5x Rounds Of:
  - 5x Single Arm Sprawl + Snatch
  - 5x Single Arm Overhead Press
  - 5x Single Arm Front Squat
  - 5x Single Arm Hang Clean + Push Press
  - 5x Single Arm Thruster


### 2021-10-29

- [x] 6x Rounds Of:
  - 10x DB Single Arm Thruster
  - 12x DB Single Arm Snatch
  - 15x Ball Slams



### 2021-10-28

- [x] 10-8-6-4-2 Reps Of:
  - DB Clean (50 lbs)
- [x] 3x 10 Reps Of:
  - D-Ball Clean + Reverse Lunge (90 lbs)
- [x] 3x 16 Reps Of:
  - DB Seated Seesaw Press (40 lbs)



### 2021-10-27

- [x] 8x Rounds Of:
  - 8x Thrusters
  - 12x Ball Slams
  - 25x Double Unders

### 2021-10-26

- [x] EMOM x21 Min
  - 20x Squats
  - 12x KB Snatches
  - 15x Push-Ups



### 2021-10-25

- [x] 11x Rounds Of:
  - 4x DB Ground-to-overhead +
  - 4x DB Suitcase Lunge (45 lbs)



### 2021-10-24

- [x] 1 min on/1 min off x 20min
  - 10x DB Deadlift
  - 8x DB DB Push Press
  - 6x DB Front Squat



### 2021-10-23

- [x] 10x Rounds Of:
  - 10x DB Single Arm Clean + Press
  - 10x DB Bench Press
  - 10x Ab Rotation



### 2021-10-22

- [x] 1x Round Of:
  - 50x Push-Ups
  - 100x Squats
  - 25x Push-ups
  - 50x Squats

### 2021-10-21

- [x] EMOM x20 Min:
  - 10x DB Snatches (60 lbs)
  - 6x Barbell Reverse Front Rack Lunges



### 2021-10-20

- [x] 4x Rounds:
  - 20x Squats
  - 10x Sit-ups
  - 10x Push-ups
  - 10x Burpees

### 2021-10-19

- [x] Clean Workout
  - Work up to heavy
    - Power Clean + Hang Clean
    - Power Clean + Jerk
  - Then 5x5 Deadlift (heavy PC&J)
  - 10x D-Ball Get-Up (40 lbs)



### 2021-10-18

- [x] EMOM x20 Min
  - 3x Back Squat (225 lbs)
  - 8x Single Arm DB Clean + Press (55 lbs)



### 2021-10-17

- [x] 6 Rounds:
  - 10x Squats
  - 8x Sit-ups
  - 6x Push-ups
  - 4x Pull-ups

### 2021-10-16

- [x] 4x rounds:
  - 50x Double-unders
  - 20x Push-ups
  - 15x Squats

### 2021-10-15

- [x] 12-9-6-3-6-9-12 reps of:
  - Burpees
  - Ball Slams

### 2021-10-14

- [x] EMOM x24 Min:
  - 12x KB Swings
  - 15x Push-Ups
  - 25x Double-Unders

### 2021-10-13

- [x] 100x Reps Of:
  - DB Single Arm Hang Power Snatch
    + DB Single Arm Push-Press
       + DB Single Arm Overhead Reverse Lung

*50x each side*



### 2021-10-12

- [x] EMOM x20 Min:
  - 10x DB Deadlift
  - 8x DB Front Squat



### 2021-10-11

- [x] 8x Rounds Of:
  - 8x Devils Press
  - 8x Ab Rotation



### 2021-10-10

- [x] 5 Rounds Of:
  - 40m Farmers Walk (DBs)
  - Weighted Sit-Ups
  - 16x Hammer Curls



### 2021-10-09

- [x] EMOM x20 Min:
  - 12x DB Alternating Snatch
  - 8x DB Clean + Push Press (from floor)

### 2021-10-08

- [x] EMOM x 20 Minutes
  - 8x DB Devils Press
  - 6x DB Squat Clean

### 2021-10-07

- [x] 6x Rounds Of:
  - 5x D-Ball Toss (150 lbs)
  - 10x DB Bench Press
  - 12x KB Swing (70 lbs)

### 2021-10-06

- [x] AMRAP x12 Minutes
  - 12x DB Push-Press
  - 10x DB Front-Squat
  - 8x DB Burpee

### 2021-10-05

- [x] EMOM x30 Minutes
  - 10x DB Thrusters L (50 lbs)
  - 10x DB Thrusters R (50 lbs)
  - 25 Double-Unders

### 2021-10-04

- [x] 8x Rounds Of:
  - 10x DB Front Squats
  - 20x DB Alternating Snatches



### 2021-10-03

- [x] 100x Reps Of:
  - Push-Ups
  - Sit-Ups
  - Ball Slams (25 lbs)

### 2021-10-02

- [x] 10 Rounds:
  - 10x DB Split-Squats
  - 10x DB Squats



### 2021-10-01

- [x] EMOM x 24 Minutes:
  - 10x DB Burpees
  - 10x DB Push-Press

## September

### 2021-09-30

- [x] 6x Rounds Of:
  - 15x Single Arm KB Swings
  - 10x Single Arm Devils Press
  - 20x Double-Unders
  - 10x Ab Rotations

### 2021-09-29

- [x] 2x Rounds Of:
  - 10x DB Single Arm Power Clean
  - 25x Double-Unders
  - 10x DB Single Arm Power Clean and Press
  - 25x Double-Unders
  - 10x DB Alternating Power Snatch
  - 25x Double-Unders



### 2021-09-28

- [x] EMOM x 20 Minutes:
  - 6x D-Ball Reverse Lunges
  - 8x D-Ball Ground-to-Over-Shoulder



### 2021-09-27

- [x] 8x Rounds Of:
  - 12x KB Swings (70 lbs)
  - 15x Push-Ups
  - 25x Double-Unders



### 2021-09-26

- [x] 1 Min On/1 Min Off x 24 Min:
  - DB Alternating Hang Power Snatch
  - DB Alternating Hang Power Clean + Push Press



### 2021-09-25

- [x] 5x Rounds Of:
  - 12x DB Bench
  - 10x Goblet Squats
  - 12x KB Swings (70 lbs)

### 2021-09-24

- [x] 6x Rounds of:
  - 12x Alternating KB Snatch
  - 20x Hammer Curls
  - 15x Bodyweight Squats

### 2021-09-23

- [x] EMOM x24 Minutes:
  - 8x Alternating DB Snatch + Thruster
  - 25x Double-Unders
  - 12x Push-Ups

### 2021-09-22

- [x] EMOM x24 Minutes:
  - 8x DB Deadlifts
  - 6x DB Hang Clean
  - 6x DB Power Clean + Push Press



### 2021-09-21

- [x] EMOM x 21 Minutes
  - 2x D-Ball Ground to Shoulder + 50ft Carry
  - 10x Alternating DB Snatch
  - 15x Push-Ups



### 2021-09-20

- [x] EMOM x20 Minutes:
  - 6x DB Hang Clean + Split Jerk (3x Right, 3x Left)

### 2021-09-19

- [x] 5x Rounds Of:
  - Heavy Bag
  - 8x DB Alternating Sprawl + Snatch
  - 8x Ab Rotation



### 2021-09-18

- [x] 1x Round For Time:
  - 30-24-22-18-14 (DB Hang Power Snatch)
  - 15-12-9-6-3 (Burpees)
  - 50-40-30-20-10 (Double-Unders)

### 2021-09-17

- [x] 20x Rounds Of:
  - 3x DB Deadlifts
  - 3x DB Hang Clean
  - 3x DB Power Clean
  - 3x DB Thrusters
  - 3x DB Front Squats



### 2021-09-16

- [x] 5x Rounds Of:
  - 6x D-Ball Lunge (90 lbs)
  - 10x Single Arm DB Bench (65 lbs)
  - 10x Hammer Curls




### 2021-09-15

- [x] 6x Rounds Of:
  - 8x DB Alt Snatch + Press
  - 6x Double KB Clean + Alt Press
  - 20x Double-Unders



### 2021-09-14

- [x] 5x Rounds:
  - 12x DB Hang Clean & Press
  - 10x DB Bent Over Rows
  - 10x Ab Rotation



### 2021-09-13

- [x] 5x Rounds Of:
  - 20x Squats
  - 20x Push-Ups

- [x] 6x Rounds Of:
  - 8x Devils Press (50 lbs)



### 2021-09-12

- [x] 100 Reps Of:
  - Push-Ups
  - Squats
  - Sit-Ups

### 2021-09-11

- [x] 10x Rounds Of:
  - 5x D-Ball Squats
  - 5x D-Ball Step-Up-And-Overs
  - 5x D-Ball Lunges



### 2021-09-10

- [x] 100x Reps Of:
  - KB Snatches
  - DB Clean & Jerk



### 2021-09-09

- [x] EMOM x24 Min
	- 8x Ground-to-Overhead
	- 12x Ball Slams
	- 8x Goblet Squats
	- 12x DB Bench



### 2021-09-08

- [x] EMOM x24 Minutes
  - 6x D-ball tosses 90 lbs
  - 12x Ball Slams 25 lbs
  - 15x Push-Ups


### 2021-09-07

- [x] Every 120 seconds x15 rounds:
  - 8x DB Deadlifts (65 lbs)
  - 8x Push-Press (65 lbs)
  - 40m D-Ball Carry


### 2021-09-06

- [x] EMOM x16 Minutes:
  - (first 8 min) 10x Alternating DB Snatch
  - (last 8 min) 10x Alternating DB Clusters

*50, 55, 65, 75 lbs*


### 2021-09-05

- [x] 6x Rounds Of:
  - 5x D-Ball Toss
  - 30x DB Curls
  - 8x Weighted Leg-lift/Floor Press
  - *abs


### 2021-09-04

- [x] 50x Reps Of:
  - 2x KB Deadlift +
    - 2x KB Clean & Jerk +
      - 2x Front Squat +
        - 2x Overhead Lunge

### 2021-09-03

- [x] 1 Round Of:
 - 10x Alt DB Clean + Press
   - (55, 65, 75 lbs)  
 - 10x Alt DB Snatch
  - (55, 65, 75 lbs)  
 - 20x Alt DB Snatch + Clean & Jerk
   - (65 lbs)  
 - 20x Alt DB Snatch + Thruster
   - (65 lbs)  
 - 3x10x DB Bench
   - (65 lbs)  



### 2021-09-02

- [x] EMOM x21 Minutes:
  - 8x Power Clean + 4x Push-Press
  - 5x DB Deadlift + 10x Push-Ups

  - 10x TGU (5x each side)



### 2021-09-01

- [x] EMOM x21 Minutes:
  - 2x DB Squat Clean + 4x Front Squats
  - 8x Clusters
  - 3x DB Power Cleans + 5x Push-Ups

## August

### 2021-08-31

- [x] Barbell Work:
  - Back Squat
    - 2x5 reps of 225 lbs  
    - 2x4 reps of 245 lbs  
    - 2x3 reps of 275 lbs  
  - Front Squat
     - 2x8 reps of 135 lbs  
     - 2x5 reps of 185 lbs  
     - 2x4 reps of 225 lbs  

  - DB bench 3x12 reps
  - Barbell curls to failure  (in squat rack)



### 2021-08-30

- [x] 10-12-15-18-15-12-10 Reps Of:
  - DB Alternating Power Snatch
  - DB Suitcase Reverse Lunge

### 2021-08-29

- [x] Barbell Horseplay
  - Power Snatch
  - Overhead squats
  - Power cleans



### 2021-08-28

- [x] 6x Rounds Of:
  - 12x Kneeling Ball-Slams
  - 8x DB Sprawl-to-Snatch
  - 12x DB Floor Press/Flies (legs lifted)



### 2021-08-27

- [x] 6x Rounds Of:
  - 6x D-Ball Clean
  - 12x DB Ground-to-Overhead



### 2021-08-26

- [x] EMOM x20 Minutes
  - 10x DB Bench Press
  - 12x Goblet Squats
  - 10x Hammer Curls (each arm)

### 2021-08-25

- [x] 5x Rounds Of:
  - 8x KB Snatch (70 lbs)
  - 25x Double-Unders
  - 12x Push-Ups



### 2021-08-24

- [x] 8x Rounds Of:
  - 8x DB Deadlift
  - 12x DB Single Arm Alternating Snatches/Cleans
  - 8x DB Push-Press



### 2021-08-23

- [x] EMOM x18 Minutes
  - 10x DB Deadlift
  - 8x Burpees

### 2021-08-22

- [x] 10-12-15-12-10 Reps Of:
  - Single Arm DB Alternating Power Snatch
  - Single Arm DB Alternating Burpee



### 2021-08-21

- [x] 6x Rounds Of:
  - 12x DB Reverse Lunge
  - 12x DB Push Press
  - 12x DB Bench Press
  - 12x Overhead Sit-ups



### 2021-08-20

- [x] 8 Rounds Of:
  - 7x Pull-Ups
  - Back Squat (8x, 5x, 4x, 3x)
  - 10x DB Clean + Press (50 lbs - 70 lbs)




### 2021-08-19

- [x] EMOM x20 Minutes:
  - 16x DB Alternating Snatches
  - 8x DB Overhead Lunge

### 2021-08-18

- [x] EMOM x18 Minutes:
  * 1x DB Clean
    + 2x DB Power Clean
      * 3x Front Squat
        + 4x Push-Press

### 2021-08-17

- [x] 5x Rounds Of:
  - 20x DB Alternating Snatch (50 lbs)
  - 20x DB Deadlifts (2x 50 lbs)



### 2021-08-16

- [x] Every Minute On The Minute (EMOM) x 20 Minutes:
  - 4x DB Squat Clean + 2x Push Jerk
  - 25x Double-Unders

### 2021-08-15

- [x] 50 reps of:
  - D-Ball Tosses (150 lbs)



### 2021-08-14

- [x] 30x Min Of:
  - Heavy Bag
  - 10x Overhead Sit-ups
  - 8x Ab Rotation



### 2021-08-13

- [x] 5x Rounds Of:
  - 12x Alternating KB Snatch
  - 10x KB Thrusters

*after each exercise, complete 40m weighted carry, preferably offset*



### 2021-08-12

- [x] 8x Rounds Of:
  - 10x DB Alternating Snatches
  - 10x DB Thrusters (5x each)
  - 6x D-Ball Bear Hug Lunges
  - 20x Double-Unders

### 2021-08-11

- [x] 4x Rounds Of:
  - 16x Alternating Front Rack DB Lunges
  - 12x Box Jump Overs
  - 8x DB Clean & Jerks

### 2021-08-10

- [x] 1x Round Of:
  - 20x Squats
  - 10x Box Jumps
  - 20x DB Power Snatches
  - 16x Squats
  - 8x Box Jumps
  - 16 DB Power Snatches
  - 12x Squats
  - 6x Box Jumps
  - 12x DB Power Snatches
  - 8x Squats
  - 4x Box Jumps
  - 8x DB Power Snatches

### 2021-08-09

- [x] 3 Rounds Of:
  - 10x DB Clean + Jerks
  - 20x GHD Sit-Ups
  - 25-Yard D-Ball Bear Hug Carry

### 2021-08-08

- [x] 5x Rounds Of:
  - 15x KB Snatches
  - 10x Ball Slams
  - 10x Box Jumps

### 2021-08-07

- [x] 6x Rounds Of:
  - 10x DB Power Cleans
  - 10x DB Ground-to-Overhead
  - 10x DB Front Squats

### 2021-08-06

- [x] EMOM x 30 Min
  - 1st 10: 20x squats
  - 2nd 10: 10x Ground-to-Overhead
  - 3rd 10: 10x Single Arm DB Power Clean and Press



### 2021-08-05

- [x] 5x Rounds Of:
  - 20x Ball Slams
  - 10x Box Jumps
  - 10x Burpees

### 2021-08-04

- [x] 3x Rounds Of:
  - 10x DB Squat Cleans
  - 8x Over-the-DBs Burpees
  - 10x KB Snatches

### 2021-08-03

- [x] 4x Rounds Of:
  - 10x DB Burpees
  - 20x KB Snatches
  - 30x Double-unders

### 2021-08-02

- [x] 100x Reps Of:
  - DB Thrusters
  - D-Ball Lunge (90 lbs), front + back

### 2021-08-01

- [x] 5 Rounds Of:
  - 10x DB Snatch
  - 5x Barbell Back Squat (135 lbs, 185 lbs, 205 lbs)
  - 8x DB Seated Press (40 lbs, 45 lbs, 50 lbs, 55 lbs)

## July

### 2021-07-31

- [x] 5x Rounds Of:
  - 5x Barbell Front Squat (135 lbs, 155 lbs, 185 lbs)
  - 12x DB Singel Arm Thruster
  - 1x Barbell Power Clean + Jerk (185 lbs)

### 2021-07-30

- [x] 1x Round Of:
  - 15x DB Power Snatches
  - 20x DB Front Squats
  - 60x Double-unders
  - 12x DB Power Snatches
  - 15x DB Front Squats
  - 50x Double-unders
  - 9x DB Power Snatches
  - 10x DB Front Squats
  - 40x Double-unders
  - 6x DB Power Snatches
  - 5x DB Front Squats
  - 30x Double-unders

### 2021-07-29

- [x] EMOM x20 Minutes:
  + 1st 10:
    - 12x DB Deadlifts
    - 12x DB Push-Press
  + 2nd 10:
    - 10x DB Suitcase Lunge
    - 12x KB Swing


### 2021-07-28

- [x] 4x Rounds Of:
  - 30x Double-unders
  - 8x DB Deadlifts
  - 10x Push-ups

### 2021-07-27

- [x] EMOM x 18 Minutes
  - 20x Double-Unders
  - 4x DB Power Clean + Jerk + Snatch (from floor)



### 2021-07-26

- [x] 10x Rounds:
  - 10x DB Bench Press
  - 20x DB Curls
  - 10x Goblet Squats


### 2021-07-25

- [x] EMOM x20 Minutes:
  - 1st 10 min: 6x DB Clusters (3x each side)
  - 2nd 10 min: 10-9-8…3-3-3 DB Snatches

*50x reps of: single arm DB Clean + Press (with opposite rack)*

### 2021-07-24

- [x] 6x Rounds
  - 10x Single Arm DB Clean and Press
  - 10x Burpees
  - 12x Single Arm Overhead Lunges

### 2021-07-23

- [x] 5x Rounds
  - 7x DB Thrusters
  - 15x Push-Ups
  - 10x KB Snatches

### 2021-07-21

- [x] EMOM x32 Minutes:
  - 8x D-Ball Tosses
  - 8x Deadlifts
  - 8x Power Cleans
  - 8x Push-Presses


### 2021-07-20

- [x] 10x Rounds:
  - 3x Devils Presses
  - 12x Alternating DB Suitcase Lunges
  - 20x Squats

### 2021-07-19

- [x] EMOM x 14 Minutes
  - 10x Thrusters
  - 20x DB Alternating Snatches


### 2021-07-18

- [x] 10x Rounds:
  - 6x D-Ball Clean (90 lbs)
  - 6x D-Ball Step-Ups (90 lbs)


### 2021-07-17

- [x] 1x Round Of:
  - 100x Alternating DB Snatch
  - 75x Alternating DB Clean & Jerk
  - 50x Single Arm DB Thrusters


### 2021-07-16

- [x] EMOM x21 Minutes:
  - 25x Double-Unders
  - 10x Double DB Snatches
  - 100m Farmer Carry

### 2021-07-15

- [x] 5x Rounds:
  - 10x KB Swings
  - 15x Goblet Squats
  - 15x Push-Ups


### 2021-07-14

- [x] 8 Rounds Of:
  - 10x Ball Slams
  - 50x Double-Unders
  - 6x D-Ball Tosses (3x 60 lbs, 3x 90 lbs)


### 2021-07-13

- [x] 12x Rounds Of:
  - 5x Pull-Ups
  - 7x Devil's Press
  - 9x Suitcase Lunges
  - 20x Double-Unders

### 2021-07-12

- [x] 8x Rounds:
  - 16x DB Curl + Press (8x Each Side)
  - 12x DB Bench
  - 12x DB Tricep Extension
  - 12x Goblet Squat


### 2021-07-11

- [x] EMOM x 21 Minutes
  - 10x Burpees
  - 12x DB Single Arm Snatches
  - 6x DB Thrusters



### 2021-07-10

- [x] 3x Rounds Of:
  - 50x Squats
  - 6x D-Ball Tosses
  - 10x DB Power Clean + Jerk

### 2021-07-09

- [x] 50x Reps Of:
  - 2x DB Ground-to-Overhead
  - 2x DB Front Squats
  - 2x DB Suitcase Lunges



### 2021-07-08

- [x] 30-20-10 Reps Of:
  - DB Deadlifts
  - Push-Ups
  - DB Front Squats

### 2021-07-07

- [x] 8x Rounds Of:
  - 14x KB Swing (70 lbs)
  - 16x DB Curls (40 lbs)
  - 18x DB Bench (45 lbs)



### 2021-07-06

- [x] EMOM x20 Minutes:
  - 12x Squats
  - 15x DB Single Arm Snatches (50 lbs)



### 2021-07-05

- [x] 8x Rounds
  - 10x Curls (each arm)
  - 10x Tricep Extensions (each arm)
  - 10x DB Rows (each arm)
  - 10x Goblet Squat
  - 10x DB Bench

### 2021-07-04

- [x] EMOM x20 Minutes:
  - 10x Single Arm Clusters
  - 30x Double-Unders
  - 10x Burpees
  - 30x Double-Unders

### 2021-07-03

- [x] 5x Rounds:
  - 8x DB Bench Press
  - 8x DB Clean
  - 8x DB Snatch + Reverse Lunge

### 2021-07-02

- [x] EMOM x25 Minutes:
  - 12x Push-Ups
  - 20x Squats
  - 12x Snatches
  - 12x Suitcase Lunges
  - 8x Single Arm Clusters

### 2021-07-01

- [x] 10x Rounds:
  - 8x DB Single Arm Clusters
  - 8x DB Deadlifts
  - 8x DB Push-Press

## June

### 2021-06-30

- [x] EMOM x20 Minutes:
  - 6x KB/DB Snatch + Thruster
  - 8x Overhead Sit-Ups

### 2021-06-29

- [x] 5x Rounds:
  - 10x TB/DB Hammer Curls
  - 10x TB/DB Strict Press
  - 10x TB/DB Goblet Squat
  - 10x TB/DB Bench Press

*then 100x DB Clean + Press 50 lbs*



### 2021-06-28

- [x] 100x Reps Of:
  - DB Thrusters (2x40 lbs)


### 2021-06-27

- [x] EMOM x18 Minutes:
  - 12x KB Snatch (53 lbs)
  - 15x Push-Ups
  - 8x D-Ball Toss (90 lbs)



### 2021-06-26

- [x] 5x Rounds:
  - 20x Squats
  - 20x Sit-Ups
  - 20x Double-Unders

### 2021-06-25

- [x] 1x Round:
  - 15-14-13-12-11-10x DB Clusters
  - 20-22-24-26-28-30x Double-Unders



### 2021-06-24

- [x] 7x Rounds:
  - 6x DB Deadlift + 12x DB Curls
  - 10x DB Curl + Press


### 2021-06-23

- [x] EMOM x 21 Minutes:
  - 12x DB Snatches
  - 10x DB Suitcase Reverse Lunges
  - 8x DB Deadlift

*all with 50 lbs
**abs



### 2021-06-22

- [x] 100x Burpees
  - *wear a weightvest*

### 2021-06-21

- [x] 8x Rounds Of:
  - 8x Devils Press
  - 12x DB Bench Press



### 2021-06-20

- [x] 5x Rounds;
  - 12x Single Arm Bulgarian Split Squat + Single Arm Push-Press
  - 12x DB Deadlift + DB Rows
  - 12x Single Arm DB Hang Snatch + Single Arm Overhead Lunge

### 2021-06-19

- [x] 10x Rounds:
  - 12x Push-Ups
  - 15x Squats
  - 20x Double-Unders
  - 10x D-Ball Tosses

### 2021-06-18

  - [x] EMOM x15 Rounds:
    - 2x Squat Cleans
    - 2x Push-Press
    - 2x Thrusters

### 2021-06-17

- [x] 8 Rounds Of:
  - 10x Goblet Squats
  - 10x TB Bench Press
  - 8x DB Rows


### 2021-06-16

- [x] EMOM x20 Minutes:
  - 2x DB Rows + 3x Devils Press + 4x Front Squat

### 2021-06-15

- [x] 12x Rounds Of:
  - 6x DB Single Arm Deadlift
  - 6x DB Hang Clean
  - 6x DB Push-Press

### 2021-06-14

- [x] 5 Rounds:
  - 20x Push-Ups
  - 20x Sit-Ups
  - 20x Squats
  - 20x Double-Unders

### 2021-06-13

- [x] 3 Rounds:
  - 10x DB Deadlifts
  - 40m DB Farmer Carry
  - 5x Strict Pull Ups
  - 10x TB/KB Push-Press
  - 40m KB Front Rack Carry



### 2021-06-12

- [x] 8x Rounds:
  - 12x Single Arm KB Snatches
  - 10x DB Plank Pull-throughs
  - 8x KB Clusters
  - 2x KB TGU



### 2021-06-11

- [x] 10x Rounds
  - 10x Curl & Press
  - 10x KB Deadlifts
  - 10x DB Bench Press
  - 10x DB Weighted Step-Ups

### 2021-06-10

- [x] 5x Rounds:
  - 5x Devils Press
  - 10x Single Arm DB Snatches
  - 10x Burpee Over DBs


### 2021-06-09

- [x] E2MOM x 9x Rounds:
  - 6x DB Push-Press + 6x DB Front Squats
  - 12x DB Single Arm Snatches + 6x DB Single Arm Overhead Lunge
  - 6x DB Deadlifts + 6x DB Hammer Curls

### 2021-06-08

- [x] 6x Rounds Of:
  - 10x KB snatches (L)
  - 10x KB snatches (R)
  - 12x Ball Slams (25 lbs)

*warm up on bag (until it breaks)*



### 2021-06-07

- [x] 3x Rounds Of:
  - 30x Squats
  - 20x DB Hang Clean & Press
  - 10x DB Single Arm Devils' Press



### 2021-06-06

- [x] 7x Rounds Of:
  - 7x Deck Squats
  - 7x Push-Ups
  - 7x KB Swings
  - 7x Toe-Touches

### 2021-06-05

- [x] EMOM x18 min:
  - 20x Double-Unders
  - 8x D-Ball

### 2021-06-04

- [x] 10x Rounds Of:
  - 8x DB Hang Snatches
  - 8x Push-Ups
  - 8x DB Goblet Squats
  - 8x Sit-Ups

### 2021-06-03

- [x] 8x Rounds Of:
  - 15x Thrusters
  - 30x Double-Unders

### 2021-06-02


- [x] Every 90 Seconds x 15:
  - 5x DB Deadlift
  - 5x DB Clean + Press
  - 5x DB Push Press

### 2021-06-01

- [x] 20-20-15-15-10-10-5-5 Reps Of:
	* KB Swings
	* SA Thruster
	* DB Bench
	
## May

### 2021-05-31

- [x] 15-12-9-6-9-12-15 Reps Of:
	* DB Burpees
	* KB Front-Rack Lunges
	* Overhead Sit-Ups
	* Goblet Squats

### 2021-05-30

- [x] 10 Rounds of:
	* 10x DB Curl and Press
	* 10x DB Goblet Squats
	* 10x DB Bench Press

### 2021-05-29

- [x] 7 Rounds of:
	* 7x Hang Power Cleans
	* 7x Thrusters
	* 7x Deadlifts

### 2021-05-28

- [x] EMOM x20 Min:
	* 5 Push-Ups
	* 10 Toe-Touches
	* 15 Squats

### 2021-05-27

- [x] 20-15-10-5 reps of:
	* Burpees
	* Squats
	* Push-ups
	* Sit-ups

*rest 2 min*

- [x] 5-10-15-20 reps of:
	* Burpees
	* Squats
	* Push-ups
	* Sit-ups

### 2021-05-26

- [x] 4 Rounds:
  - 12x DB Power Cleans
  - 30x Sit-Ups
  - 12x DB Thrusters

### 2021-05-25

- [x] EMOM for 20 Min:
  - 10x Ball Slams (25 lbs)
  - 10x Burpees

### 2021-05-24

- [x] 5 Rounds:
  - 5x Dual DB Hang Snatch
  - 10x Dual DB FR Squat
  - 5x Dual G-2-OH
  - 10x Dual DB Thruster
  - 5x Dual DB Hang Clean & Press
  - 10x DB Deadlift

### 2021-05-23

- [x] 3 Rounds:
  - 15 KB Deadlifts
  - 12 KB Clean
  - 9 DB Front Squat
  - 6 DB Snatch

### 2021-05-22

- [x] 6 Rounds Of:
  - 12x KB Swing
  - 12x DB Split Squat
  - 12x DB Bench Press


### 2021-05-21

- [x] 6 Rounds Of:
  - 12x DB Deadlift (50 lbs)
  - 12x DB Push-Press (50 lbs)
  - 12x DB Goblet Squat (50 lbs)


### 2021-05-20

<*basketball game*>

- [x] 6 Rounds:
  - 12 Alt DB Snatches
  - 12 Burpees
  - 12 DB Thrusters

### 2021-05-19

- [x] 5 Rounds:
  - 15x Push-Ups
  - 20x Squats
  - 12x KB Swings (70 lbs)

  * Then 10 TGU (5x 53, 5x 70)



### 2021-05-18

- [x] 10 Rounds:
  - 5x DB Snatch + Front Squat (50 lbs)
  - 5x Single Arm DB Bench Press (85 lbs)

### 2021-05-17

- [x] 6 Rounds:
  - 12x Goblet Squats
  - 14x TB Seated Curls
  - 20x Double-Unders

### 2021-05-16

- [x] 100 Reps Of:
  - DB Snatches (50 lbs)
- [x] 50 Reps Of:
  - D-Ball Tosses (90 lbs)



### 2021-05-15

<*rest*>

- [x] 5-10-15-20-15-10-5 Reps Of:
  - KB Goblet Squats
  - KB Push-Press
  - DB Row
  - KB Cleans

### 2021-05-14

- [x] EMOM x 15 Minutes:
  - 6x Double DB Snatch + Double DB Clean (40 lbs)
  - 6x Burpee-Over-DBs



### 2021-05-13

- [x] 6 Rounds Of:
  - 20x Squats  
  - 12x TB Seated Curls  
  - 12x DB Bench  

### 2021-05-12

- [x] 5x Rounds Of:
  - 10x DB Thrusters
  - 20x DB Offset Lunges (One Up/One Down)
  - 30x Double-Unders

### 2021-05-11

<*rest day*>

- [x] 5 Rounds Of:
  - 10x KB Snatches
  - 12x Weighted Sit-Ups
  - 14x PushUps
  - 25x Double-Unders

### 2021-05-10

- [x] EMOM x20 Minutes
  - 5x Single Arm DB Snatch + 5x Single Arm DB Overhead Lunge (R)
  - 5x Single Arm DB Snatch + 5x Single Arm DB Overhead Lunge (L)

*Supplemental Ab Work*

### 2021-05-09

- [x] EMOM x10 Minutes
  - 20x KB Switch-Hand-Swings
  - 5x TB Snatch + Thruster

### 2021-05-08

- [x] 5-10-15-20-15-10-5 Reps Of:
  - Double-Unders
  - DB Clean & Front Squat

### 2021-05-07

- [x] 100 Reps Of:
  - Devil's Thruster (40 lbs)

### 2021-05-06

- [x] 8x Rounds Of:
  - 40x Meter Farmer Walk (2x 53 lbs)
  - 16x Seated Curl & Press
  - 25x Double-Unders

### 2021-05-05

- [x] EMOM x22 Min:
  - 10x KB Swings
  - 6x DB Burpees

*Supplemental Ab Work*

### 2021-05-04

- [x] 10x Rounds Of:
  - 10x Sit-Ups
  - 15x Push-Ups
  - 20x Squats
  - 25x Double-Unders

### 2021-05-03

Warm Up:

- [x] perfect your jump shot!

Workout:  

- [x] EMOM x 21 Min   
  - 25x Double-Unders   
  - 10x DB Split Squat   
  - 12x DB Bench Press   

### 2021-05-02

- [x] 50x Reps Of:
  - D-Ball Tosses (90 lbs)
  - Ground-To-Overhead (45 lbs)

### 2021-05-01

- [x] EMOM x 24 Min
  - 10x Lateral Burpees Over DBs
  - 10x Weighted Step-Ups
  - 10x Single Arm DB Clean & Jerks

## April

### 2021-04-30

- [x] 5x Rounds Of:
  - 10x Banded Bicep Curls
  - 10x Banded Tricep Pull-Downs
  - 10x KB Goblet Squats
  - 10x Hand-Release Push-Ups
  - 10x Reverse Crunches

### 2021-04-29

- [x] Warm Up:
  - Rope x 2 Songs
  - Shoulders (Bands)
  - Hips (Sling Shot)


- [x] 10-9-8-7-6-5-4-3-2-1 Reps Of:
  - Push-Press (45 lbs)
  - KB Swings (70 lbs)
  - Ball Slams (25 lbs)



### 2021-04-28

- [x] 5x Rounds Of (Warm Up):
  - 20x Push-Ups
  - 20x Squats

- [x] 1 Round Of:
  - 50x KB Deadlift (*5 Sets Of 10*)
  - 40x KB Clean (*5 Sets Of 8*)
  - 30x KB Push-Press (*6 Sets Of 5*)
  - 20x KB Front Squat (*4 Sets Of 5*)
  - 10x KB Cluster (*however you can*)

*Supplemental Ab Work*



### 2021-04-27

- [x] 3-6-9-12-15 Reps Of:
  - Squats
  - Push-Ups
  - Overhead Sit-Ups

- [x] 3-6-9-12-15 Reps Of:
  - Burpees
  - Reverse Lunges
  - Step-Ups


### 2021-04-26

- [x] EMOM x 28 Min
  - 10x Single Arm DB Thruster (R 45 lbs)
  - 15x KB Swings (70 lbs)
  - 10x Single Arm DB Thruster (L 45 lbs)
  - 15x KB Swings (70 lbs)

(*Supplemental Ab Work*)


### 2021-04-25

- [x] 5x Rounds Of:
  - 25x Double-Unders
  - 20x Squats
  - 15x Push-Ups

*Add 25 lbs Weight-Vest*
*4x Sets Of 10 Reps Supplemental Ab Work*


### 2021-04-24

- [x] EMOM x 20 Min
  - 4x Burpees
  - 6x Squats
  - 8x Sit-Ups

### 2021-04-23

- [x] 3-6-9-12-15 Reps Of:
  - DB Thrusters
  - Alternating DB Snatch
*20m Carry after each Round*


### 2021-04-22

- [x] 8x Rounds Of:
  - 25x Double-Unders
  - 12x Goblet Squats (50 lbs)
  - 12x DB Press (50 lbs)


### 2021-04-21

- [x] EMOM x 32 Min:
  - 12x KB Swings (70 lbs)
  - 10x DB Suitcase Lunge (50 lbs)
  - 10x DB Deadlift (50 lbs)
  - 15x Push-Ups



### 2021-04-20

- [x] 4 Rounds:
  - 20x KB Swings
  - 20x DB Snatches
  - 10x D-Ball Tosses

### 2021-04-19

- [x] EMOM x24 Min
  - 12x Ball slams (25 lbs)
  - 10x Ground-to-Overhead (35 lbs)
  - 30 Sec Scorpion Bag


### 2021-04-18

- [x] Squat Workout (Barbell)
  - 10x Reps 135 lbs (Front & Back Squat)
  - 8x Reps 185 lbs (Front & Back Squat)
  - 6x Reps 205 lbs (Front & Back Squat)
  - 4x Reps 225 lbs (Front & Back Squat)

### 2021-04-17

- [x] EMOM x24 Min
  - 25x Double-Unders
  - 5x D-Ball Tosses (90 lbs)
  - 10x KB Snatches (70 lbs)

### 2021-04-16

- [x] 3 Rounds:
  - 30x Squats
  - 20x DB Hang Power Clean + Jerk
  - 10x Single Arm Devil's Press

### 2021-04-15

- [x] 10 Rounds:
  - 8x Alternating DB Snatch
  - 10x Lateral Burpees (Over DBs)

### 2021-04-14

- [x] Every 45 Seconds x 50 Cycles
  - DB Renegade Rows (2x)
  - DB Push-Up
  - DB Devil's Press
  - DB Thruster

### 2021-04-13

- [x] 15-12-9-12-15 Reps Of:
  - KB Swings
  - Burpess (Over KBs)

### 2021-04-12

- [x] 50x Reps Of The following:
  - DB Burpee
  - DB Power Clean + Push-Press

### 2021-04-11

- [x] 10 Rounds
  - 10x Push-Ups
  - 12x Squats
  - 15x Sit-Ups

### 2021-04-10

- [x] 8x Rounds
  - 10x Push-Ups
  - 12x Squats
  - 15x Sit-Ups

### 2021-04-09

- [x] 10 Rounds
  - 10x DB Single Arm Snatches
  - 10x DB/TB Floor Press
  - 6x Weighted Step-Ups

### 2021-04-08

- [x] Squat Workout:
  - 8x Front Squat 135 lbs x2
  - 8x Back Squat 135 lbs x2
  - 6x Back Squat 185 lbs x2
  - 6x Back Squat 185 lbs x2
  - 5x Back Squat 225 lbs
  - 5x Back Squat 225 lbs

### 2021-04-07

- [x] 8x Rounds:
  - 2x KB Combo (4x Total):
    - Single Arm Swing + Snatch + Cluster (53 lbs)
  - 8x D-Ball Tosses (90 lbs)



### 2021-04-06

- [x] EMOM x24 Min
  - 8x DB Deadlift
  - 8x DB Hang Clean & Jerk
  - 25x Double-Unders

*50 lbs DB shown*



### 2021-04-05

- [x] 8x Rounds Of:
  - 8x DB Front Squats
  - 8x DB Front Rack Lunges
  - 8x DB Thrusters

### 2021-04-04

- [x] 10-9-8-7-6-5-4-3-2-1 Reps Of:
  - DB Deadlift
  - DB Hang Power Clean
  - DB Push Jerks

### 2021-04-03

- [x] 50 Reps Of (55 lbs):
  - DB Snatch + Reverse Lunge
  - DB Snatch + Reverse Lunge + Press
  - DB Split Snatch (Catch in Reverse Lunge)

- [x] 25 Reps Of:
  - heavy DB Snatch (85 lbs)



### 2021-04-02

- [x] 4x Rounds:
  - 10x DB Hang Power Clean & Jerk
  - 10x Renegade Row
  - 25x Double-Unders

- [x] Squats!!!
  - 12x KB Swings
  - 3x8 135 lbs Front Squat + Back Squat
  - 12x KB Swings
  - 4x7 185 lbs Front Squat + Back Squat
  - 12x KB Swings
  - 5x5 225 lbs Front Squat + Back Squat
  - 12x KB Swings



### 2021-04-01

- [x] 1-2-3-4-5-6-7-8-9-10 Reps Of:
  - Single Arm DB Deadlift
  - Single Arm DB Snatch (From Floor)
  - Single Arm DB Thruster
  - Single Arm DB Push-Press

*Cardio*

## March

### 2021-03-31

- [x] 20x Rounds Of:
  - 5x DB Snatch
  - 4x DB Overhead Lunge
  - 3x SA DB Push-Press
  - 2x SA DB Front Squat
  - 1x SA DB Thruster

*50 lbs DB shown*

### 2021-03-30

- [x] EMOM x 18 Min
  - 12x Push-Ups
  - 12x Squats

### 2021-03-29

- [x] EMOM x 16 Min
  - 11x Push-Ups
  - 11x Squats

### 2021-03-28

- [x] EMOM x 14 Min
  - 11x Push-Ups
  - 11x Squats

### 2021-03-27

- [x] EMOM x 12 Min
  - 10x Push-Ups
  - 10x Squats

### 2021-03-26

- [x] EMOM x 10 Min
  - 10x Push-Ups
  - 10x Squats

### 2021-03-25

- [x] 6x Rounds
  - 15x Squat
  - 12x Push-Ups
  - 9x Sit Ups
  - 6x Lunges
  - 3x Pull Ups

### 2021-03-24

- [x] 1x Round:
  - 100x Squats
  - 80x Sit-Ups
  - 60x Lunges
  - 40x Push-Ups
  - 20x Burpees

### 2021-03-23

- [x] 50 Reps Of:
  - 30x D-Ball Clean & Toss (90 lbs)
  - 20x D-Ball Clean & Toss (150 lbs)

*toss it Over a 30 inch box*

### 2021-03-22

- [x] Gym Workout   
  - 50 KB Swings  
  - 50 Sling Shot Squats    
  - Front Squats (135 x 5, 185 x 5, 195 x 5, 225 x 4 x 2)  
  - Power Clean + Hang Full Clean (185 x 5, 195 x 5)  

### 2021-03-21

- [x] Every 90 Seconds x 10 Cycles:

  - 3x Single Arm Snatch (Each Side)
  - 6x Push-Ups
  - 9x Squats

### 2021-03-20

- [x] 10x Rounds Of:
  - 5x DB Hang Full Squat Clean
  - 5x DB Thrusters
  - 5x DB Push-Press

### 2021-03-19

- [x] 8x Rounds Of
  - 4x 150 lbs D-Ball Tosses
  - 10x Weighted Step-Ups

### 2021-03-18

- [x] 6x Rounds
  - 8x DB Hang Full Squat Clean
  - 12x KB Snatches

- [x] 10x Rounds:
  - 4 Reps Of:
   { DB Snatch +
     Thruster +
     Hammer Curl +
     Press
   } = 1 Rep



### 2021-03-17

  - [x] EMOM x 22 Min
  - 4 Reps Of:
  {
    + Single Arm DB Renegade Row (Row + Push-Up)
    + Single Arm Cluster
   } = 1 Rep

### 2021-03-16

- [x] EMOM x 16 Min:
  - 20x KB Swings
  - 15x Push-Ups

### 2021-03-15

- [x] Every 90 Seconds x 10 Cycles:
{ - Renegade Row
  - Devils Press
  - Push-Press} = x 3 Reps

For as many Rounds as possible\*:
- 6x D-Ball Tosses 150 lbs

\*complete all 6 under 30 Seconds.



### 2021-03-14

- [x] Boxing Workout
  - 20 Min Focus Mitts
  - 20 Min Heavy Bag

### 2021-03-13

- [x] 5x Rounds Of
  - 10x TB Snatches
  - 10x KB Snatches
  - 10x DB Snatches



### 2021-03-12

- [x] 50 Reps Of:
  - 1x Devil's Press
  - 2x Alternating DB Snatches
  - 4x DB Overhead Lunges

### 2021-03-11

- [x] 5x Rounds Of:
  - 6x D-Ball Tosses
  - 10x Weighted Step-Ups
  - 25x Double-Unders
  - 20x DB Floor Press
  - 10x DB Deadlifts

### 2021-03-10

- [x] 50 Reps Of:
- 3x DB Alternating Snatches
- 2x DB Alternating Thrusters
- 1x DB Snatch

### 2021-03-09

- [x] EMOM x 24 Min
  - 15x Bodyweight Squat
  - 12x KB Swings
  - 15x PushUps
  - 12x Goblet Reverse Lunge

### 2021-03-08

- [x] 50 Reps Of:
 {- 2x DB Single Arm Cleans
  - 2x DB Single Arm Push-Press
  - 2x DB Thrusters} = 1 Rep

### 2021-03-07

- [x] 5x Rounds:
  - 8x Hang Power Clean & Jerk
  - 8x Front Rack Lunge
  - 8x Ground-to-Overhead
  - 40m Farmer Carry

### 2021-03-06

- [x] 1 Hour Bag Work
  - Scorpion Bag (3 Min Round x10)
  - Heavy Bag (3 Min Round x10)

### 2021-03-05

- [x] 6 Rounds:
  - 6x D-Ball Tosses (90 lbs)
  - 10x DB Curl & Press (45 lbs)
  - 10x DB Snatches (55 lbs)
  - 12x Weighted sit-Ups (25 lbs)



### 2021-03-04

- [x] **AM Workout:**  
*had access to gym, took advantage*   
  - 3 Sets/5 Reps Barbell Back Squat 135 lbs  
  - 3 Sets/5 Reps Barbell Front Squat 135 lbs  
  - 12 KB Swing 53 lbs  
  - 2 Sets/5 Reps Barbell Back Squat 185 lbs  
  - 2 Sets/5 Reps Barbell Front Squat 185 lbs  
  - 12 KB Swing 53 lbs  
  - 1 Set/5 Reps Barbell Back Squat 225 lbs  
  - 1 Set/5 Reps Barbell Front Squat 225 lbs  
  - 12 KB Swing 53 lbs  
  - 3 Sets/5 Reps Of Barbell Power Snatch 135 lbs  
  - 40 meter sled drag ~250 lbs (4 Reps)   

- [x] **PM Workout:** 24 Min EMOM     
  - 15x Squats   
  - 6x D-Ball Tosses   
  - 15x Push-Ups   
  - 12x DB Push-Press   


### 2021-03-03

- [x] 8x Rounds
  - 8x DB Snatch + Thruster
  - 12x KB Swings

### 2021-03-02

- [x] For Time
  - 10x DB Squat + Tricep Extensions
  -  8x DB Double Front Rack Squat + Reverse Lunge
  - 10x DB Arnold Press (Curl + Press) From Knees
  - 8x DB Alternating Chinese Row



### 2021-03-01

- [x] 20 Min EMOM
  - 12x DB Hang Clean & Press
  - 10x DB Suitcase Walking Lunges
  - 12x Push-Ups
  - 10x Squats

## February

### 2021-02-28

- [x] 10-9-8-7-6-5-4-3-2-1 Reps Of:
  - DB Snatch
  - Sit-Ups
  - DB Single Arm Thruster
  - Lunges



### 2021-02-27

- [x] 50 Reps Of:
  - 4x Devil's Clean
  - 3x Front Squats
  - 2x DB Hang-to-Overhead

### 2021-02-26

- [x] For Time (24 Min Time-Cap)

10-15-20-15-10 Reps Of:
  - DB Burpee
  - Single Arm DB Hang Clean & Jerk

30-30-30-30-30 Reps Of:
  - Double-Unders

### 2021-02-25

- [x] 10x Rounds
  - 10x Push-Ups
  - 8x Goblet Reverse Lunges
  - 10x KB Swings
  - 6x D-Ball Tosses

### 2021-02-24

- [x] 10x Min EMOM
  - 10x Squats
  - 8x Box Jumps
- [x] 15x Min EMOM
  - 10x Single Arm Overhead Reverse Lunge
  - 10x Alternating Single Arm DB Hang Clean & Press
  - 20x Double-Unders


### 2021-02-23

- [x] EMOM x24 Min
  - 10x DB Goblet Squats
  - 8x Single Arm Devil's Press
  - 10x Step-Ups
  - 8x Sit-Ups


### 2021-02-22

- [x] EMOM x 21 Min
  - 3 Single Arm DB Snatches (Each Arm)
  - 6 Push-Ups
  - 9 Squats

### 2021-02-21

- [x] 7x Rounds
  * 10x DB Single Arm Clean & Jerk
  * 25x Double-Unders
  * 8x Weighted Sit-Ups



### 2021-02-20

- [x] Every 3 Min x 7 Rounds
  * 8x DB Ground To Overhead
  * 8x KB Snatches
  * 30x Double-Unders

### 2021-02-19

- [x] Every 3 Min x 7 Rounds
  * 10x DB Thrusters
  * 8x KB Swings
  * 25x Double-Unders

### 2021-02-18

- [x] Every 3 Min x 7 Rounds
  * 10x DB Thrusters
  * 8x KB Swings

### 2021-02-17

- [x] 8x Rounds
  * 8x DB Deadlift + DB Curl & Press (45 lbs)
  * 8x DB Goblet Squats (85 lbs)

### 2021-02-16

- [x] 8x Rounds
  - 6x Alternating DB Hang Cleans
  - 12x DB Push-Press
  - 15x Sit-Ups

### 2021-02-15

- [x] 8x Rounds:
  - 10x D-Ball Tosses (90 lbs)
  - 10x DB Snatches (55 lbs)
  - 5x Overhead Lunge (55 lbs)

### 2021-02-14

- [x] 25-20-15-10-5
  - Squats
  - DB Hang Power Clean & Press
  - DB Deadlift

### 2021-02-13

- [x] 20-15-10-5
  - Alternating DB Snatches

- [x] 5-10-15-20
  * Push-Ups


### 2021-02-12

- [x] 3 Rounds
  * 10x DB Snatch (L)
  * 10x DB OH Lunges (L)
  * 10x DB Snatch (R)
  * 10x DB OH Lunges (R)
  * 10x DB Power Cleans (L)
  * 10x DB Front Squats (L)
  * 10x DB Power Cleans (R)
  * 10x DB Front Squats (R)

### 2021-02-11

- [x] 7 Rounds:
  - 15x KB Swing
  - 12x DB Floor Press
  - 20x Squats

### 2021-02-10

- [x] 6x Rounds:
  - 8x Thrusters
  - 10x Ball Slams
  - 16x Hammer Curls
  - 12x Ab Rotation

### 2021-02-09

- [x] 7x Rounds
  - 3x DB Deadlift
  - 1x DB Clean
  - 2x DB Split Jerks
  - 2x DB Cleans
  - 2x DB Front Squats
  - 2x DB Jerks

### 2021-02-08

- [x] 10x Rounds
  - 10x DB Snatches (55 lbs)
  - 6x D-Ball Tosses (90 lbs)

### 2021-02-07

- [x] 12-10-8-6-4-2
  * KB Swing > Clean > Squat (One Arm)
- [x] 2-4-6-8-10-12
  * DB Snatch > Sprawl (One Arm)

### 2021-02-06

- [x] 10-9-8-7-6-5-4-3-2-1
  * KB Snatch > Switch Hand Swing > Snatch
  * KB Clean > Single Arm Front Squat

- [x] 8x Reps (4 Each leg)

### 2021-02-05

- [x] 5x Rounds
  * 15x Z Press
  * 15x DB Goblet Squats
  * 15x Box Jumps
  * 15x OH Walking Lunge

### 2021-02-04

- [x] 5x Rounds
  * 9x Double KB Front Squat
  * 7x KB Swings
  * 5x KB Push-Press

### 2021-02-03

- [x] 5 Rounds (20 Min Time-cap)
  - 10x DB Clusters
  - 10x Push-Ups
  - 10x Sit-Ups (25 lbs)
  - 6x D-Ball Tosses (90 lbs)

### 2021-02-02

- [x] EMOM x 21 Min
  - 15x Push-Ups
  - 25x Double-Unders
  - 12x Single Arm DB Snatch (55 lbs)

### 2021-02-01

- [x] 5x Rounds
  * 15x KB Swings
  * 15x Goblet Squats
  * 10x KB Snatches
  * 10x KB Push-Press

## January

### 2021-01-31

- [x] 50 Reps Of Each
  - Goblet Squat (55 lbs)
  - Cross-Carry Lunge (50 lbs)
  - DB Snatch (Double) (50 lbs)

### 2021-01-30

- [x] 5x Rounds
  - 10x DB Snatch (R)
  - 10x DB Front Squat (in right Hand)
  - 10x DB Snatch (L)
  - 10x DB Front Squat (in left Hand)

### 2021-01-29

- [x] 6-12-18-12-6 Reps
  - KB Alternating Switch Hand Swings
  - DB Thrusters

### 2021-01-28

- [x] 50x Reps Of:
  - 150 lbs D-Ball Tosses
  - DB Hang Power Clean & Press (45 lbs)


### 2021-01-27

- [x] Every 90 Seconds for 12 Cycles
  * 10x Ball Slams (25 lbs)
  * 5x D-Ball Tosses (150 lbs)

### 2021-01-26

- [x] EMOM x 24 Min
  - 8x D-Ball Tosses (4x 60 lbs, 4x 90 lbs)
  - 2x TGU (55 lbs)
  - 20x Squats


### 2021-01-25

- [x] Every 30 Seconds for 3 Min
  * 8x Heavy Goblet Squats
- [x] Every 45 Seconds for 6 Cycles
  * 10 Single Arm Thrusters (5 Each Side)
- [x] EMOM x 5 Min
  * 12 Single Arm Overhead Walking Lunges

### 2021-01-24

- [x] EMOM x10 Min
  * 10x D-Ball Tosses
  * 10x KB Swing

### 2021-01-23

- [x] Every 2 Min x 10 Cycles
  * 10x Clusters
  * 8x Box Jumps

### 2021-01-22

- [x] 50 Reps Of Each:
  - DB Alternating Double Thruster
  - DB Single Arm Split Snatch
  - DB Floor Press

### 2021-01-21

- [x] 8x Rounds
  - 10x Overhead Sit-Up (25 lbs)
  - 12x DB Snatches (55 lbs)
  - 6x D-Ball Tosses (90 lbs)

### 2021-01-20

- [x] 21 Min EMOM
  - 5x DB Clusters (45 lbs)
  - 12x Ball Slams (25 lbs)
  - 12x KB Swings (53 lbs)


### 2021-01-19

- [x] EMOM x24 Min
  - 10x DB Hang Clean & Press (55 lbs)
  - 15x Squats
  - 10x DB Snatch (55 lbs)
  - 15x Push-Ups


### 2021-01-18

- [x] 10x Rounds
  * 10x DB Clusters
  * 30x Double-Unders

### 2021-01-17

- [x] 8x Rounds:
  - 10x D-Ball Up & Over (90 lbs)
  - 12x DB Hang Snatch (55 lbs)
  - 10x Ball Slams (25 lbs)
  - 10x DB Curl & Press (45 lbs)


### 2021-01-16

- [x] D-Ball EMOM x 27 Min:
  - 8x D-Ball Lunges
  - 8x D-Ball Squats
  - Complex: 2x Reverse Lunge, 3x Squats


### 2021-01-15

- [x] 4 Rounds:
  * 10x Double-DB Snatch
  * 25x Double-Unders

### 2021-01-14

- [x] 10 Rounds:
  - 10x KB Snatches (53 lbs)
  - 6x DB Goblet Squats (85 lbs)


### 2021-01-13

- [x] 21 Min EMOM
  - 20x Banded Squats
  - 12x DB Snatch (55 lbs)
  - 15x Push-Ups


### 2021-01-12

- [x] EMOM x 20Min
  * 20x Single Arm DB Snatch
  * 30x Double-Unders
  * 10x DB Burpees
  * 30x Double-Unders

### 2021-01-11

- [x] 20 Min EMOM
  - Odd Min (Scorpion Bag)
  - Even Min (Heavy Bag)

(25 lbs weight vest)


### 2021-01-10

- [x] 4x Rounds
  * 15x Goblet Squats
  * 20x Single Arm DB Thruster (R)
  * 25x Double-Unders
  * 15x Goblet Squats
  * 20x Single Arm DB Thruster (L)
  * 25x Double-Unders

### 2021-01-09

- [x] 100x Reps Of
  * 90 lbs D-Ball Tosses
  * Push-Ups

### 2021-01-08

- [x] 8x Rounds:
  - 10x Overhead Sit-Ups (25 lbs)
  - 8x DB Thruster (45 lbs)
  - 6x D-Ball Tosses (90 lbs)

### 2021-01-07

- [x] EMOM x 20 Min
2 Reps Of:
  - Single Arm DB Snatch
  - Single Arm DB Cluster
  - Single Arm DB Devil’s Press

All From Floor

### 2021-01-06

- [x] 100x Reps Of:
  - Turkish Get-Ups (53 lbs)

### 2021-01-05

- [x] EMOM x 24 Min
  - 6x D-Ball Tosses 150 lbs
  - 12x Ball Slams 25 lbs
  - 6x D-Ball Tosses 90 lbs


### 2021-01-04

- [x] 24 Min EMOM
  - Push-Ups x 15
  - Swings x 15
  - Jabs x 30 Seconds
  - DB Ground To Overhead x 6 (85 lbs)


### 2021-01-03

- [x] 5 Rounds:
  * 10x Deadlifts
  * 15x Cleans
  * 25x Snatches

### 2021-01-02

- [x] Every 90 Seconds x 15 Sets
  - 6x D-Ball Tosses (150 lbs or 90 lbs)
  - 20x Banded Squats
  - 20x Weighted Step-Ups
  - 20x Double-Unders

### 2021-01-01

- [x] Snatch-tastic! (100x Reps Of The Following)
  * DB Snatch (55 lbs)
  * KB Snatch (53 lbs)
  * TB Snatch (53 lbs)
