---
title: "The Daily Dose (2023)"
output:
  html_document:
    theme: default
    highlight: textmate
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: yes
---

***Currently under development***

> *2023 was a big year (new wife, new baby, new house, etc.) so not all workouts were recorded. Those that were are all on [Vimeo](https://vimeo.com/user124837051).*

## December

Starting in December, the workouts took place in the AZ garage gym:

### 2023-12-31

-   [x] [50x Reps:](https://vimeo.com/manage/videos/899037372)

    -   150lb D-Ball Tosses

### 2023-12-30

-   [x] [Heavy Bag + DB Complex:](https://vimeo.com/manage/videos/898829529)
    -   1,2,1 
    -   1,2,3,2
    -   DB Alt Hang Clean + Snatch*
    -   1,2,1 + 1,2,3,2 

*65lbs

### 2023-12-28

-   [x] [Heavy bag (15x 90 sec rounds):](https://vimeo.com/manage/videos/898614814)

    -   1, 2, 3 + low, high combos

### 2023-12-27

-   [x] [7x Rounds:](https://vimeo.com/manage/videos/898364749)

    -   10x DB Deadlifts*
    
    -   10x DB Hang Power Snatch*

*all with 65lbs

### 2023-12-26

-   [x] [EMOM x16 Min:](https://vimeo.com/898007048)

    -   8x DB Squats

    -   8x DB Hang Power Clean + Press

### 2023-12-25

-   [x] [ENOM x15 Min:](https://vimeo.com/897813929)

    -   DB Devils Press

    -   DB Squat

    -   DB Hang Clean + Rev Lunge (x2)

    -   DB Hang Clean + Press

### 2023-12-24

-   [x] [15x Rounds Heavy Bag (90 sec on/off):](https://vimeo.com/897666582)

    -   1s, 2s, and 3s

### 2023-12-23

-   [x] [15x Rounds (90 sec on/off):](https://vimeo.com/897666866)

    -   1s and 2s

### 2023-12-22

-   [x] [15x Rounds (90 sec on/off):](https://vimeo.com/897343216)

    -   All Left Hand

### 2023-12-21

-   [x] [8x Rounds Of:](https://vimeo.com/897257551)

    -   10x TB Snatch

    -   3x TB Complex:

        -   Hang Clean + Hang Power Clean + Press

### 2023-12-19

-   [x] [12x Rounds Of:](https://vimeo.com/896708666)

    -   3x Devils Press

    -   5x DB Squat

    -   7x DB Push-Up\*

\*45lbs first 6 min, 55lbs last 6 min

### 2023-12-18

-   [x] [8x Rounds Of:](https://vimeo.com/896707682)

    -   4x D-Ball Tosses (150lbs)

    -   6x DB Bench Press (65lbs)

### 2023-12-17

-   [x] [AMRAP x10 Min:](https://vimeo.com/896706850)

    -   [x] 5x DB Ground-To-Overhead

### 2023-12-16

-   [x] [5x Rounds Of:](https://vimeo.com/895595682)

    -   3 min heavy bag

    -   AMRAP DB complex

    -   DB Squat Clean + Rev DB Lunge

### 2023-12-15

-   [x] [1 Min On/1 Min Off:](https://vimeo.com/895594940)

    -   10x DB Bench Press

    -   10x DB Alternating Snatch

### 2023-12-12

-   [x] [EMOM x16 Min:](https://vimeo.com/895593976)

    -   10x DB Deadlifts\*

    -   4x Single Arm Hang Clean + Press\*

\*65lbs first 8 min, 75lbs last 8 min

### 2023-12-11

-   [x] [AMRAP x15 Min:](https://vimeo.com/895586169)

    -   5x Devils Press (50lbs)

### 2023-12-10

-   [x] [7x Rounds Of:](https://vimeo.com/894972330)

    -   10x DB Bench Press

    -   10x DB Squats

### 2023-12-09

**PM**

-   [x] [6x Rounds Of:](https://vimeo.com/892978386)

    -   10x DB Snatch (65lbs)

    -   16x Curls (40lbs)

**AM**

-   [x] [EMOM x16 Min:](https://vimeo.com/892965949)

    -   5x DB Clean\*

\*55lbs first 8 rounds, 65lbs last 8 rounds

### 2023-12-07

-   [x] [8x Rounds Of:](https://vimeo.com/892958009)

    -   10x DB Deadlifts

    -   10x DB Hang Clean and Press

    -   10x DB Squats

### 2023-12-04

-   [x] [4x Rounds:](https://vimeo.com/891170908)

    -   3 min bag

    -   3 min DB Squats

## November

The workouts below took place in the PDX home (office) gym:

### 2023-11-21

-   [x] [Until Failure:](https://vimeo.com/887113052)

    -   10x DB Hang Full Clean

### 2023-11-18

-   [x] [For time:](https://vimeo.com/886147611)

    -   100x Devils Press

### 2023-11-17

-   [x] [AMRAP x18 Min:](https://vimeo.com/885840649)

    -   12x DB Alt Hang Power Snatch

    -   10x DB Squats

### 2023-11-15

-   [x] [EMOM x20 Min:](https://vimeo.com/885842114)

    -   5x DB Squat Cleans

### 2023-11-14

-   [x] [10x Rounds:](https://vimeo.com/884660845)

    -   10x DB Squats

    -   10x DB Push-Press

    -   10x DB Deadlifts

### 2023-11-13

-   [x] [AMRAP in 10 Min:](https://vimeo.com/884220297)

    -   5x Devils Press

### 2023-11-12

-   [x] [AMRAP in 20 Min:](https://vimeo.com/883797106)

    -   16x DB Alt Hang Snatch

    -   8x DB Rev Lunge

### 2023-11-10

-   [x] [EMOM x20 Min:](https://vimeo.com/883797667)

    -   10x DB Squats

    -   5x Power Clean + Press

### 2023-11-07

-   [x] [AMRAP x15 Min:](https://vimeo.com/882303522)

    -   10x DB Deadlift

    -   6x Dbl DB Hang Clean + Press

### 2023-11-04

-   [x] [15x Rounds Of:](https://vimeo.com/881247857)

    -   DB Burpee

    -   DB Clean + Press (from floor)

\*3x reps = 1 round

### 2023-11-02

-   [x] [AMRAP x20 Min:](https://vimeo.com/880744202)

    -   10x DB Deadlifts

    -   10x DB Squats

### 2023-11-01

-   [x] [EMOM x10 Min:](https://vimeo.com/880390472)

    -   5x Dbl DB Clean

## October

### 2023-10-31

-   [x] [EMOM x24 Min:](https://vimeo.com/880510945)

    -   12x Push-Ups

    -   20x Squats

    -   15x Sit-Ups

    -   5x Devils Press

### 2023-10-30

-   [x] [EMOM x18 Min:](https://vimeo.com/879605334)

    -   8x DB Deadlifts

    -   12x DB Alt Hang Power Snatch

    -   8x DB Squats

### 2023-10-26

-   [x] [8x Rounds:](https://vimeo.com/878481289)

    -   8x Hang Power Snatch

    -   10x DB Lunge

### 2023-10-24

-   [x] [EMOM x16 Min:](https://vimeo.com/877765371)

    -   10x DB Push-Ups

    -   8x DB Thrusters

### 2023-10-23

-   [x] [12x Rounds:](https://vimeo.com/877319502)

    -   6x DB Hang Power Clean\*
        -   (3x each side)
    -   6x DB Hang Power Snatch\*
        -   (3x each side)
    -   8x DB Rev Lunge

\*hold DB in Front rack

### 2023-10-21

-   [x] [EMOM x20 Min:](https://vimeo.com/876765246)
-   3x Sets of:
    -   DB H Power Snatch
    -   DB Front Squat
    -   DB Curl (x2)

### 2023-10-20

-   [x] [EMOM x20 Min:](https://vimeo.com/876582306)

    -   3x DB Deadlift

    -   3x DB Hang Clean

    -   3x DB Push-Press

### 2023-10-19

-   [x] [8x Rounds:](https://vimeo.com/876215964)

    -   12x Push-Ups

    -   8x DB Squats

### 2023-10-18

-   [x] [6x Rounds:](https://vimeo.com/875853123)

    -   8x DB Power Clean + Press

\*15 min time-cap

### 2023-10-16

-   [x] [EMOM x15 Min:](https://vimeo.com/875016265)

    -   20x Squats

    -   12x DB Alt Snatch

    -   15x Sit-Ups

### 2023-10-15

-   [x] [EMOM x20 Min:](https://vimeo.com/874696006)

    -   2x Push-Up/Row + Push-Up

    -   2x DB Front Squat

    -   2x DB Hang Clean

    -   2x DB Push-Press

### 2023-10-14

-   [x] [AMRAP in 18 Min:](https://vimeo.com/874463313)

    -   DB Complex:

        -   3x DB Power Clean

        -   3x DB Front Squat

        -   3x DB Snatch

        -   2x DB Over Head Lunge

        -   3x DB Snatch

        -   3x DB Hang Power Clean + Press

### 2023-10-10

-   [x] [AMRAP x12 Min:](https://vimeo.com/873138548)

    -   5x DB Burpees

    -   8x DB Thrusters

### 2023-10-09

-   [x] [EMOM x18 Min:](https://vimeo.com/872736859)

    -   2x DB Alt Hang Snatch

    -   2x Over Head Rev Lunge

    -   2x DB Alt Hang Power Clean + Press

    -   2x Over Head Rev Lunge

### 2023-10-08

-   [x] [EMOM x18 Min:](https://vimeo.com/872557208)

    -   3 Sets Of:
        -   DB Hang Power Clean
        -   DB Hang Power Snatch
        -   DB Front Squat

### 2023-10-07

-   [x] [Every 45 sec x12 Rounds:](https://vimeo.com/872613654)

    -   5x DB Thrusters

### 2023-10-05

-   [x] [EMOM x15 Min:](https://vimeo.com/871650531)

    -   8x DB Rev Lunge (suitcase grip)

    -   8x Dbl DB Hang Snatch

### 2023-10-03

-   [x] [EMOM x15 Min:](https://vimeo.com/870877184)

    -   12x DB Alt Snatch

    -   12x DB Over-Head Sit-Up

    -   20x Squats

### 2023-10-02

-   [x] [10x Rounds Of:](https://vimeo.com/871651632)

    -   10x DB Push-Ups

    -   10x DB Deadlifts

### 2023-10-01

-   [x] [For time:](https://vimeo.com/871652457)
    -   50x DB Hang Clean + Press

## September

### 2023-09-30

-   [x] [AMRAP x20 Min:](https://vimeo.com/869734460)

    -   12 DB Alt Snatch 
  
    -   10x Rev DB Lunge


### 2023-09-28

-   [x] [EMOM x20 Min:](https://vimeo.com/869379418)

    -   5x DB Power Clean + Press


### 2023-09-26

-   [x] [AMRAP x20 Min](https://vimeo.com/868557189)

    -   5x DB Devils Press 
    
    -   12x DB Plank Press 
    
    -   12x DB Curl


### 2023-09-25

-   [x] [8x Rounds Of:](https://vimeo.com/868523203)

    -   10x DB Deadlifts  
    
    -   5x DB Hang Power Clean + Press


### 2023-09-23

-   [x] [EMOM x18 Min:](https://vimeo.com/868522588)

    -   15x DB Alt Snatch 
    
    -   20x Squats 
  
    -   15x Sit-Ups


### 2023-09-22

-   [x] [10x Rounds Of:](https://vimeo.com/868522893)

    -   5x Clusters 
    
    -   12x DB OH Sit-Up

### 2023-09-14


-   [x] [1 Min On/1 Min Off:](https://vimeo.com/864685843)

    -   Single Arm Snatch + Front Squat + Hang Power Clean + Push Press


### 2023-09-13

-   [x] [EMOM x20 Minutes:](https://vimeo.com/864687099)

    -   5x DB Deadlifts + Hang Clean

### 2023-09-11

-   [x] [EMOM x20 Min:](https://vimeo.com/863392789)

    -   2x DB Complex
        -   Squat x 2
        -   Suitcase Lunge x 2
        -   Snatch x 2

Throwback to: https://vimeo.com/466993599

*4x8 reps DB Overhead Sit-up

### 2023-09-10

-   [x] [50x reps:](https://vimeo.com/863062717)

    -   Bear complex:
        -   Deadlift + Clean + Front Squat + Push-Press + Front Squat + Push-Press 
        
    -   50x reps of: 
        -   DB Power Clean + DB Snatch

*Repeat of 2020-12-28

### 2023-09-09

-   [x] [For time:](https://vimeo.com/862890065)
      -   100x DB Hang Power Snatch   
      -   75x DB Bridge Press   

### 2023-09-08

-   [x] [8x Rounds:](https://vimeo.com/862887375)

    -   8x DB Thrusters

### 2023-09-06

-   [x] [8x Rounds Of:](https://vimeo.com/862137977)

    -   5x Devils Press 
    
    -   8x DB Squat


### 2023-09-05

-   [x] [7x Rounds Of:](https://vimeo.com/862196221)

    -   10x DB Deadlifts 
    
    -   2x Ground-to-Overhead + 2x Overhead Reverse Lunge


### 2023-09-04

-   [x] [10x Rounds Of:](https://vimeo.com/861058291)

    -   5x Dbl DB Hang Clean + Press 
    
    -   5x Rev DB Lunge


### 2023-09-02

-   [x] [5x Rounds Of:](https://vimeo.com/860656009)

    -   16x DB Alt Snatch 
    
    -   15x Squats
  
    -   12x SA Overhead Sit-Ups


### 2023-09-01

-   [x] [EMOM x20 Min:](https://vimeo.com/860475196)

    -   3x of: 
        -   DB Deadlift 
        -   DB Pwr Clean 
        -   DB Squat 
        -   DB Push-Press
        
## August

### 2023-08-31

-   [x] [100x Reps:](https://vimeo.com/860464538)
    -   Squats  
    -   DB Alt Hang Power Snatch   
    -   Push-Ups  


### 2023-08-30

-   [x] [EMOM x20 Min:](https://vimeo.com/860466824)
    -   5x Devils Press   
    -   10x DB Squat  
    -   5x Devils Clean & Press  
    -   10x DB Rev Lunge  


### 2023-08-28

-   [x] [AMRAP in 15 Min:](https://vimeo.com/859150312) 
    -   10x Dbl DB Hang Power Snatch  
    -   15x Squats  

### 2023-08-27

-   [x] [6x Rounds Of:](https://vimeo.com/858436972) 
    -   6x DB Power Clean + Press   
    -   6x DB Squat   
    -   6x DB Over Head Sit-Up   

### 2023-08-26

-   [x] [5x Round Of:](https://vimeo.com/858463148)
    -   10x DB Deadlifts  
    -   10x Push-Ups  
    -   8x DB Hang Snatch   
    -   8x Push-Ups   
    -   6x Devils Press   
    -   6x Push-Ups   

### 2023-08-24

-   [x] [AMRAP in 20x Min:](https://vimeo.com/857692015)
    -   5x Clusters 
    -   10x DB Hang Clean + Press 
    -   12x DB Rev Lunge

### 2023-08-22

-   [x] [EMOM x12 Min:](https://vimeo.com/856982749)  
    -   20x Squats 
    -   14x DB Hang Power Snatch 
    -   8x DB Over Head Sit-Up


### 2023-08-21

-   [x] [EMOM x 20 min:](https://vimeo.com/856397643)
    -   5x DB Deadlifts 
    -   5x DB Push-Press
    -   10x DB Front Rack Rev Lunge

### 2023-08-19

-   [x] [30 sec on/30 sec off (until failure):](https://vimeo.com/856186810)
    -   Dbl DB Devils Press + DB Squat


### 2023-08-18

-   [x] [5x Rounds Of:](https://vimeo.com/856185149)
    -   20x Squats
    -   20x Push-Ups 
    -   20x DB Alt Snatch*

*10x from hang/10x from floor


### 2023-08-16

-   [x] [5x Rounds Of:](https://vimeo.com/856166225)
    -   12x DB Alt Snatch 
    -   12x DB Goblet Rev Lunge

### 2023-08-15

-   [x] [50x Reps For Time:](https://vimeo.com/856163598)
    -   DB Devils Press

### 2023-08-14

-   [x] [Every 90 sec x 18 min:](https://vimeo.com/854651049)
    -   3x DB Deadlift 
    -   3x DB Hang Power Clean 
    -   6x DB Rev Lunge 
    -   6x DB Curls


### 2023-08-13

-   [x] [50 Reps of*:](https://vimeo.com/854344951)
    -   Snatch
    -   Clean + Press 
    -   Overhead Rev Lunge (x2)
    -   Thruster 

*each side = 1 rep

### 2023-08-12

-   [x] [AMRAP x 12 min:](https://vimeo.com/854052074)
    -   10x DB Hang Clean + Press


### 2023-08-11

-   [x] [12x Rounds:](https://vimeo.com/853887743)
    -   3x Devils Press 
    -   5x DB Squat 
    -   7x Push-Ups

### 2023-08-10

-   [x] [8x Rounds Of:](https://vimeo.com/853531149)   
    -   12x DB Alt Snatch   
    -   12x Sit-Ups   


### 2023-08-09

-   [x] [AMRAP (15 min):](https://vimeo.com/853150340)
    -   5x DB Deadlift  
    -   5x DB Hang Power Clean   
    -   5x DB Squat  
    -   10x DB Bench/Plank Press  


### 2023-08-08

-   [x] [EMOM x 15 Min:](https://vimeo.com/852855025)
    -   5x DB Hang Clean + Press

### 2023-08-06

-   [x] [Chipper:](https://vimeo.com/852660641)
    -   100x Squats 
    -   100x Push-ups 
    -   50x Dbl DB Bulgarian Split Squat
    -   75x DB Alt H Power Snatch
    -   50x DB Alt H Power Clean + Press


### 2023-08-05

-   [x] [8x Rounds Of:](https://vimeo.com/852007582) 
    -   8x Dbl DB Snatch  
    -   8x Dbl DB Rev Lunge  

*4x sets of: 

- DB Hammer Curl (til failure)

### 2023-08-04

-   [x] [10x Rounds Of:](https://vimeo.com/851836307)
    -   5x DB Deadlifts   
    -   5x DB H P Clean + Press  
    -   5x DB Squats  


### 2023-08-03

-   [x] [6x Rounds For Time:](https://vimeo.com/851486582)
    -   12x SA DB Alt Power Snatch    
    -   12x DB Rev Goblet Lunge       
    -   12x SA DB Alt Power Clean + Press   
    -   12x DB Goblet Lunge   

### 2023-08-01

-   [x] [10x Rounds:](https://vimeo.com/850746847)
    -   5x DB Deadlift 
    -   5x DB Thruster
    


## July

### 2023-07-31


-   [x] [5x Rounds:](https://vimeo.com/850411896)
    -   20x DB Alt SA Snatch
    -   7x Dbl DB Clean + Jerk*

*from floor


### 2023-07-30

-   [x] [7x Rounds:](https://vimeo.com/849961475) 
    -   10x DB Squats 
    -   8x DB SA Press


### 2023-07-29

-   [x] [AMRAP in 16 Min:](https://vimeo.com/849647825)
    -   5x Dbl DB Snatch 
    -   10x Dbl DB Rev Lunge*

*in rack position


### 2023-07-26

-   [x] [10x Rounds of:](https://vimeo.com/849639821)
    -   3x Devils Press 
    -   5x DB Squat 
    -   7x Push-ups


### 2023-07-25

-   [x] [7x Rounds:](https://vimeo.com/848852770) 
    -   5x DB Ground-2-Overhead 
    -   10x DB Deadlift

### 2023-07-24

-   [x] [EMOM x12 Min:](https://vimeo.com/848254562)
    -   16x DB Hang Power Snatch
    -   12x DB Hang Power Clean + Press

### 2023-07-23

 
-   [x] [5x Rounds:](https://vimeo.com/847780206) 
    -   10x (push-ups, squats, sit-ups)
    -   10x bridge DB press 
    -   10x Dbl DB Clean*
    -   10x Dbl DB Snatch*

*don’t set it down

### 2023-07-22

-   [x] [EMOM x20 Min:](https://vimeo.com/847646615)
    -   1x DB Deadlift 
    -   2x Reverse Lunges 
    -   5x DB Hang Clean + Press

### 2023-07-19

-   [x] [AMRAP x10 Minutes:](https://vimeo.com/846805386)
    -   5x DB Snatch + DB Squat 
    -   2x DB TGU

### 2023-07-18

-   [x] [7x Rounds Of:](https://vimeo.com/846446397) 
    -   5x Devils Press 
    -   10x DB Rev Lunge 
    -   8x DB H Power Clean + Press

### 2023-07-17

-   [x] [EMOM x16 Min:](https://vimeo.com/846098215)
    -   12x DB Snatch 
    -   8x DB Squat


### 2023-07-12

-   [x] [5x Rounds Of:](https://vimeo.com/844761609) 
    -   10x DB Snatch 
    -   10x DB Overhead Rev Lunge 
    -   4x Dbl DB Rev Lunge*

*one up/one rack


### 2023-07-10

-   [x] [AMRAP x12 Min:](https://vimeo.com/844069774)
    -   5x DB Snatch +  
    -   5x DB Squat +  
    -   5x DB Push-Press


### 2023-07-09

-   [x] [6x Rounds:](https://vimeo.com/843677388) 
    -   5x Devils Press 
    -   5x DB Squat


### 2023-07-07

-   [x] [AMRAP x 18 Min:](https://vimeo.com/843380694) 
    -   6x Devils’ Rev Lunge 
    -   6x DB Combo: 
        -   Alt DB Snatch + Hang Power Clean & Press


### 2023-07-06

-   [x] [5x Rounds:](https://vimeo.com/843069577)
    -   12x DB Deadlift
    -   9x DB Hang Power Clean
    -   6x DB Shoulder-2-Overhead

### 2023-07-05

-   [x] [4x Rounds:](https://vimeo.com/842870920)
    -   20x DB Alt Snatch 
    -   12x Goblet Squat 
    -   8x Devils Clean & Press


### 2023-07-03

-   [x] [6x Rounds:](https://vimeo.com/842034896) 
    -   3x DB Clean 
    -   3x DB Snatch 
    -   3x Rev Lunge 
    -   3x Lunge 

*DB wood-choppers (3x8 reps)


### 2023-07-02

-   [x] [EMOM x18 Min:](https://vimeo.com/841726360)
    -   4x reps of: 
        -   DB P Snatch (Double)
        -   DB OH/Rack Rev Lunge

### 2023-07-01

-   [x] [EMOM x15 Min:](https://vimeo.com/841566150) 
    -   5x DB Deadlift 
    -   5x DB Thrusters


```{=html}
<!--

## June

### 2023-06-30


### 2023-06-29


### 2023-06-28


### 2023-06-27


### 2023-06-26


### 2023-06-25


### 2023-06-24


### 2023-06-23


### 2023-06-22


### 2023-06-21


### 2023-06-20


### 2023-06-19


### 2023-06-18


### 2023-06-17


### 2023-06-16


### 2023-06-15


### 2023-06-14


### 2023-06-13


### 2023-06-12


### 2023-06-11


### 2023-06-10


### 2023-06-09


### 2023-06-08


### 2023-06-07


### 2023-06-06


### 2023-06-05


### 2023-06-04


### 2023-06-03


### 2023-06-02


### 2023-06-01

## May

### 2023-05-31


### 2023-05-30


### 2023-05-29


### 2023-05-28


### 2023-05-27


### 2023-05-26


### 2023-05-25


### 2023-05-24


### 2023-05-23


### 2023-05-22


### 2023-05-21


### 2023-05-20


### 2023-05-19


### 2023-05-18


### 2023-05-17


### 2023-05-16


### 2023-05-15


### 2023-05-14


### 2023-05-13


### 2023-05-12

# CF (PDX)

The workouts below took place at CrossFit Primal Energy (in PDX):

### 2023-05-11


### 2023-05-10


### 2023-05-09


### 2023-05-08


### 2023-05-07


### 2023-05-06


### 2023-05-05


### 2023-05-04


### 2023-05-03


### 2023-05-02


### 2023-05-01

## April

### 2023-04-30


### 2023-04-29


### 2023-04-28


### 2023-04-27


### 2023-04-26


### 2023-04-25


### 2023-04-24


### 2023-04-23


### 2023-04-22


### 2023-04-21


### 2023-04-20


### 2023-04-19


### 2023-04-18


### 2023-04-17


### 2023-04-16


### 2023-04-15


### 2023-04-14


### 2023-04-13


### 2023-04-12


### 2023-04-11


### 2023-04-10


### 2023-04-09


### 2023-04-08


### 2023-04-07


### 2023-04-06


### 2023-04-05


### 2023-04-04


### 2023-04-03


### 2023-04-02


### 2023-04-01

## March

### 2023-03-31


### 2023-03-30


### 2023-03-29


### 2023-03-28


### 2023-03-27


### 2023-03-26


### 2023-03-25


### 2023-03-24


### 2023-03-23


### 2023-03-22


### 2023-03-21


### 2023-03-20


### 2023-03-19


### 2023-03-18


### 2023-03-17


### 2023-03-16


### 2023-03-15


### 2023-03-14


### 2023-03-13


### 2023-03-12


### 2023-03-11


### 2023-03-10


### 2023-03-09


### 2023-03-08


### 2023-03-07


### 2023-03-06


### 2023-03-05


### 2023-03-04


### 2023-03-03


### 2023-03-02


### 2023-03-01

## February

### 2023-02-28


### 2023-02-27


### 2023-02-26


### 2023-02-25


### 2023-02-24


### 2023-02-23


### 2023-02-22


### 2023-02-21


### 2023-02-20


### 2023-02-19


### 2023-02-18


### 2023-02-17


### 2023-02-16


### 2023-02-15


### 2023-02-14


### 2023-02-13


### 2023-02-12


### 2023-02-11


### 2023-02-10


### 2023-02-09


### 2023-02-08


### 2023-02-07


### 2023-02-06


### 2023-02-05


### 2023-02-04


### 2023-02-03


### 2023-02-02


### 2023-02-01

## January

### 2023-01-31


### 2023-01-30


### 2023-01-29


### 2023-01-28


### 2023-01-27


### 2023-01-26


### 2023-01-25


### 2023-01-24


### 2023-01-23


### 2023-01-22


### 2023-01-21


### 2023-01-20


### 2023-01-19


### 2023-01-18


### 2023-01-17


### 2023-01-16

### 2023-01-16 

[6 Rounds of:](https://vimeo.com/793638101)

  - 5x Deadlifts (295lbs)    
  - 8x Sandbag lunge (100lbs)    

### 2023-01-15 

[For time:](https://vimeo.com/793668886)

Work up to heavy 5x5 of:   

  - Back Squat    
  - Front Squat    

Mix with:   

  - 12x DB Hang Power Snatch    
  - 10x DB Alternating bench Press  
  

### 2023-01-14

[EMOM x 20 minutes:](https://vimeo.com/799298435)
   
  - Power Clean   
  - Push jerk    
  - Front Squat    
  - Split jerk    

*205 lbs

-->
```
